blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/inertiajs/inertia/discussions/new?category=ideas
    about: 'Suggest ideas in our discussion forums.'
  - name: Help
    url: https://github.com/inertiajs/inertia/discussions/new?category=help
    about: 'Ask questions and get help in our discussion forums.'
